framework:
  workflows:
    order_process:
      type: 'workflow'
      marking_store:
        type: 'method'
        property: 'state'
      supports:
        - App\Entity\Order
      initial_marking: new
      places:
        - new
        - accepted
        - not_paid
        - paid
        - collected
        - not_collected
        - sent
        - finished
      transitions:
        accept:
          from: new
          to: accepted
        pay_new:
          from: new
          to: [new, paid]
        pay_accepted:
          from: accepted
          to: [accepted, paid]
        collect:
          from: accepted
          to: [accepted, collected]
        send:
          from: [accepted, paid, collected]
          to: sent
        deliver:
          from: sent
          to: finished
