framework:
  workflows:
    order_process:
      type: 'state_machine'
      marking_store:
        type: 'method'
        property: 'state'
      supports:
        - App\Entity\Order
      initial_marking: new
      places:
        - new
        - accepted
        - paid
        - sent
        - finished
      transitions:
        accept:
          from: new
          to: accepted
        pay:
          from: accepted
          to: paid
        send:
          guard: 'subject.isCollected()'
          from: paid
          to: sent
        deliver:
          from: sent
          to: finished
